### ISSUE TITLE
 java.lang.IllegalStateException: Required view 'pull_to_refresh' with ID 2131296341 for field 'pullToRefresh' was not found.

### ISSUE THREAD

**Issue by suzukaze** [gfx/Android-Helium#3]
Runtime Error:

```
03-02 09:20:37.338    4907-4907/com.github.gfx.hatebulet E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.github.gfx.hatebulet, PID: 4907
    java.lang.IllegalStateException: Required view 'pull_to_refresh' with ID 2131296341 for field 'pullToRefresh' was not found. If this view is optional add '@Optional' annotation.
            at butterknife.ButterKnife$Finder.findRequiredView(ButterKnife.java:135)
            at com.github.gfx.hatebulet.fragment.HatebuEntryFragment$$ViewInjector.inject(HatebuEntryFragment$$ViewInjector.java:13)
            at com.github.gfx.hatebulet.fragment.HatebuEntryFragment$$ViewInjector.inject(HatebuEntryFragment$$ViewInjector.java:8)
            at butterknife.ButterKnife.inject(ButterKnife.java:317)
            at butterknife.ButterKnife.inject(ButterKnife.java:274)
            at com.github.gfx.hatebulet.fragment.HatebuEntryFragment.onCreateView(HatebuEntryFragment.java:80)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:486)
            at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1441)
            at android.view.View.measure(View.java:16497)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16497)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16497)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16497)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16497)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16497)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
            at android.view.View.measure(View.java:16497)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Loo
```

ButterKnife cannot access `id:pull_to_refresh` view

```Java
View view = inflater.inflate(R.layout.fragment_entry, container, false);
```

https://github.com/gfx/Android-Hatebulet/blob/master/app/src/main/java/com/github/gfx/hatebulet/fragment/HatebuEntryFragment.java#L78

Is it correct that I change `R.layout.fragment_entry` to `R.layout.fragment_entry_grid` ?
fragment_entry_grid.xml has `id:pull_to_refresh`

```Java
View view = inflater.inflate(R.layout.fragment_entry_grid, container, false);
```

- Question

There is not res/layout/fragment_entry.xml. Is there R.id.fragment_entry? (not build error)

**Comment by gfx** [comment]
Please try the latest one!

FYI: `R.id.fragment_entry` is an alias defined in `vaues*/refs.xml` to use GridView in tablets.

**Comment by suzukaze** [comment]
> Please try the latest one, clearing old build objects.

This error has not raise.

> FYI: R.id.fragment_entry is an alias defined in vaues*/refs.xml to use GridView in tablets.

I understand it. Thank you.
